/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAvatar: typeof import('bootstrap-vue-next/components/BAvatar')['BAvatar']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
  }
}
